openapi: 3.0.0
info:
  title: VOLCANOE  API DOC
  description: An Express Volcanoe API
  version: 1.0.0
  

servers:
  - url: http://myapi.us-east-1.elasticbeanstalk.com/
    description: Production server 

 
components:
  securitySchemes:
    ApiTokenss:        # arbitrary name for the security scheme
          
      type: http
      scheme: bearer
    
    ApiKey:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: apikey

  schemas:
    User:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: The user email
        password:
          type: string
          description: The user password
      example:
        email: johndoe@gmail.com
        password: password


    Volcanoe:
      type: object
      required:
        - Region
        - Number
        - Volcanoe_Name
        - Country
        - Location
        - Latitude
        - Longitude
        - Elevation
        - Type
        - Status
      properties:
        Region:
          type: string
          description: The volcanoe region
        Number:
          type: string
          description: The volcanoe number
        Volcanoe_Name:
          type: string
          description: The volcanoe name
        Country:
          type: string
          description: Country the volcanoe Occured
        Location:
          type: string
          description: The location of the volcanoe
        Latitude:
            type: string
            description: The Latitude of the volcanoe
        Longitude:
            type: string
            description: The Longitude of the volcanoe
        Elevation:
            type: string
            description: The volcanoe Elevation
        Type:
            type: string
            description: The type of volcanoe
        Status:
            type: string
            description: The volcanoe status
      example:
        Region: West Indies
        Number: 1600-21-
        Volcanoe_Name: Piparo
        Country: Trinidad
        Location: Trinidad
        Latitude: 10
        Longitude: -61
        Elevation: 140
        Type: Mud Volcanoe
        Status: Historical


tags:
  - name: Users
    description: Users of the Volcanoe API
  - name: Volcanoes
    description: A Volcanoe API  

   
paths:
  /auth/register:
    post:
      summary: Create a new user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: The user was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Some server error
 
  
  /auth/login:
    post:
      summary: Login a user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Some server error

  
  /auth/logout:
    delete:
      summary: Delete a user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: The user was deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Some server error
 
 

  
  /google:
    get:
      tags:
       - OAUTH
      summary: Render the Google authentication page.
      description: Renders the Google authentication page for the user to log in with their Google account.
      responses: 
        '200':
          description: Google authentication page rendered successfully.
          schema:
            type: string
        '400':
          description: Bad Request

  
  /success:
    get:
      tags:
      - OAUTH
      summary: Get the user profile data.
      description: Returns the user profile data after successful authentication.
      responses: 
        '200':
          description: User profile data retrieved successfully.
          schema:
            type: object
        '400':
          description: Bad Request


  
  /error:
    get:
      tags:
       - OAUTH
      summary: Handle authentication error.
      description: Returns an error message when there is an error during authentication.
      responses: 
        '200':
          description: Error message returned successfully.
          schema:
            type: string
        '400':
          description: Bad Request

  
  /auth/google:
    get:
      tags:
       - OAUTH
      summary: Authenticate with Google.
      description: Initiates the authentication process with Google using PassportJS.
      responses: 
        '200':
          description: Initiates the authentication process with Google using PassportJS.
          schema:
            type: string
        '400':
          description: Bad Request 

  
  /auth/google/callback:
    get:
      tags:
       - OAUTH
      summary: Authenticate user with Google OAuth and redirect to success page
      description: This endpoint initiates Google OAuth authentication flow and redirects the user to the success page upon successful authentication.
      responses: 
        '200':
          description: A success message indicating the user has been authenticated
          schema:
            type: object
        '400':
          description: Bad Request 

  
  
  /create/volcanoes:
    post:
      summary: Create a new volcanoe
      tags: [Volcanoes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Volcanoe'
      responses:
        '200':
          description: The volcanoe was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volcanoe'
        '500':
          description: Some server error
  
  
  /volcanoes/{id}:
    put:
      summary: Update a volcanoe by the id
      tags: [Volcanoes]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The volcanoe id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Volcanoe'
      responses:
        '200':
          description: The volcanoe was updated succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volcanoe'
        '404':
          description: The volcanoe was not found
        '500':
          description: Server error
 
  
  /volcanoes/{deleteid}:
    delete:
      summary: Remove the volcanoe by id
      tags: [Volcanoes]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The volcanoe id
      responses:
        '200':
          description: The volcanoe was deleted successfully
        '404':
          description: The volcanoe was not found
  
  
  /volcanoes/{getid}:
    get:
      summary: Get the volcanoe by id
      tags: [Volcanoes]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The volcanoe id
      responses:
        '200':
          description: Get a volcanoe by id successful
          contens:
            application/json:
              schema:
                $ref: '#/components/schemas/Volcanoe'
        '404':
          description: The volcanoe was not found
 
  
  /volcanoes:
    get:
      summary: Returns the list of all the volcanoes
      tags: [Volcanoes]
      responses:
        '200':
          description: The list of all the volcanoes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Volcanoe'
        '404':
          description: Not found

      
 